# Generated by Django 2.1.7 on 2023-03-24 00:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230323_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 3, 23, 21, 26, 57, 85937)),
        ),
    ]
